services:
  - type: worker
    name: maythushar1
    env: docker
    dockerfilePath: ./Dockerfile
    plan: pro plus
    region: singapore
    buildCommand: pip3 install --no-cache-dir --upgrade --requirement requirements.txt
    envVars:
      - key: API_ID
        value: "20078321"
      - key: API_HASH
        value: "c8ed904e4aac83cea1f27b73984debad"
      - key: BOT_TOKEN
        value: "7418613978:AAFqB9D2P1NNl1_rx5vRkFj1_wVV8O1xYSs"
      - key: MONGO_DB_URI
        value: "mongodb+srv://pyaesone:pyaesone@pyaesone.ii8wsxo.mongodb.net/?retryWrites=true&w=majority"
      - key: OWNER_ID
        value: "1318826936"
      - key: LOGGER_ID
        value: "-1002335122520"
      - key: STRING_SESSION
        value: "BQEyXvEAmSyLMdCjHuXM99EAvcdvsdwH_JqZkvYkbaU7LJc8BFvaRM6Ik1qwBKY7NcTGq_hKXI8z-yVZxAUVF3sBm490t3NdYTF5rXxoV6Fo6CdBr4-bpBQK5zpxlTMIiY-20D3D6hspcpBiFvWNAXMfZXw08ikmN1lMeIF22j2F9F8zg14eXMMgADL51D7Yjb2REpLnkCEo1cyeRPgeoOahmAP-W4L7fUj6XbxACX0zoeKeCPWLL6CWLf6AumOe2tZojvBCcHCT_yL-13C8lnUO7AfyEHpiAIDRBGVH1hj4cCit11DhyaNoyHo2GpZK9w9moRxy_cQErMyfzoZ9NKhKMe03YQAAAAFeh0k2AA"
